// File generated by FlutterFire CLI & customized for Campus Lost & Found
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVJwktPmqLM3fvOhDdH_09S6Dpxr7MJyY',
    appId: '1:765099671074:web:007c0a9fa6abc3697ad47b',
    messagingSenderId: '765099671074',
    projectId: 'campus-lost-found-app-9440c',
    authDomain: 'campus-lost-found-app-9440c.firebaseapp.com',
    storageBucket: 'campus-lost-found-app-9440c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVJwktPmqLM3fvOhDdH_09S6Dpxr7MJyY',
    appId: '1:765099671074:android:007c0a9fa6abc3697ad47b',
    messagingSenderId: '765099671074',
    projectId: 'campus-lost-found-app-9440c',
    storageBucket: 'campus-lost-found-app-9440c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVJwktPmqLM3fvOhDdH_09S6Dpxr7MJyY',
    appId: '1:765099671074:ios:007c0a9fa6abc3697ad47b',
    messagingSenderId: '765099671074',
    projectId: 'campus-lost-found-app-9440c',
    storageBucket: 'campus-lost-found-app-9440c.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVJwktPmqLM3fvOhDdH_09S6Dpxr7MJyY',
    appId: '1:765099671074:ios:007c0a9fa6abc3697ad47b',
    messagingSenderId: '765099671074',
    projectId: 'campus-lost-found-app-9440c',
    storageBucket: 'campus-lost-found-app-9440c.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );
}
